version: '3.3'
services:
  hello:
    image: buddbro/hydra-hello
    ports:
      - "3000:3000"
    depends_on:
      - "redis"
  friend:
    image: buddbro/hydra-friend
    ports:
      - "3001:3001"
    depends_on:
      - "redis"
  enemy:
    image: buddbro/hydra-enemy
    ports:
      - "3002:3002"
    depends_on:
      - "redis"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"